// Эти переменные будут инициализированы в main.js
let seasonalCanvas, seasonalCtx, seasonalCanvasWidth, seasonalCanvasHeight;
let seasonalParticles = [];
let lastParticleTime = Date.now();
let baseSeasonalParticleCount = 50; // Значение по умолчанию, будет пересчитано

function initSeasonalEffects(canvasElement, context) {
    seasonalCanvas = canvasElement;
    seasonalCtx = context;
    resizeSeasonalCanvas();
}

function resizeSeasonalCanvas() {
    if (!seasonalCanvas) return;
    seasonalCanvasWidth = window.innerWidth;
    seasonalCanvasHeight = window.innerHeight;
    seasonalCanvas.width = seasonalCanvasWidth;
    seasonalCanvas.height = seasonalCanvasHeight;

    baseSeasonalParticleCount = Math.min(PARTICLE_SETTINGS.MAX_PARTICLES, Math.max(PARTICLE_SETTINGS.MIN_PARTICLES, Math.floor(seasonalCanvasWidth * seasonalCanvasHeight / PARTICLE_SETTINGS.BASE_COUNT_FACTOR)));
    createSeasonalParticles();
}


function createSeasonalParticles() {
    seasonalParticles = [];
    const date = getCurrentDateInternal(); // Нужна функция получения текущей даты из main.js
    const month = date.getMonth();
    const day = date.getDate();
    const currentMonthData = MONTHS_CONFIG[month];
    const isCurrentlyNewYear = (month === 11 && day === 31) || (month === 0 && day === 1);

    switch (month) {
        case 0: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.8; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 2 + Math.random() * 4, d: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.6, drift: 0.6 + Math.random() * 1.6, opacity: 0.6 + Math.random() * 0.4, type: 'snow', arms: 6 + Math.floor(Math.random() * 2) * 2, detail: Math.random() > 0.7 }); }
          break;
        case 1: 
          for (let i = 0; i < baseSeasonalParticleCount * 1.5; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 1.5 + Math.random() * 3, d: Math.random() * Math.PI * 2, speed: 2 + Math.random() * 4, drift: 2 + Math.random() * 3, opacity: 0.4 + Math.random() * 0.6, type: 'snow', turbulence: 0.3 + Math.random() * 0.7, arms: 5 + Math.floor(Math.random() * 3), detail: false }); }
          break;
        case 2: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.3; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 1 + Math.random() * 2, d: Math.random() * Math.PI * 2, speed: 1 + Math.random() * 2, drift: 0.2 + Math.random() * 0.8, opacity: 0.3 + Math.random() * 0.3, type: 'snow', melting: true, arms: 6 }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.7; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, length: 8 + Math.random() * 15, speed: 12 + Math.random() * 8, opacity: 0.2 + Math.random() * 0.3, type: 'rain' }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.2; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: seasonalCanvasHeight - (Math.random() * seasonalCanvasHeight * 0.4), r: 40 + Math.random() * 60, opacity: 0.05 + Math.random() * 0.1, type: 'mist', speed: 0.1 + Math.random() * 0.2 }); }
          break;
        case 3: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.4; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, length: 6 + Math.random() * 12, speed: 10 + Math.random() * 6, opacity: 0.15 + Math.random() * 0.2, type: 'rain' }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.25; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 3 + Math.random() * 5, drift: 0.3 + Math.random() * 0.7, speed: 0.7 + Math.random() * 1.2, color: ['#FFB7C5', '#FF7BAC', '#FFC0CB', '#FFDBF1', '#ffffff'][Math.floor(Math.random() * 5)], rotation: Math.random() * Math.PI * 2, rotationSpeed: (Math.random() - 0.5) * 0.02, type: 'petal' });}
          for (let i = 0; i < baseSeasonalParticleCount * 0.15; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 1 + Math.random() * 1.5, color: '#90EE90', opacity: 0.6 + Math.random() * 0.3, speed: 0.1 + Math.random() * 0.3, drift: 0.1 + Math.random() * 0.3, type: 'bud' });}
          break;
        case 4: 
          if (Math.random() < 0.5) {
            for (let i = 0; i < baseSeasonalParticleCount * 1.5; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, length: 15 + Math.random() * 25, speed: 20 + Math.random() * 15, opacity: 0.3 + Math.random() * 0.3, type: 'rain' }); }
            for (let i = 0; i < 2 + Math.random()*2; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: 0, opacity: 0.9, type: 'lightning', nextStrike: 3000 + Math.random() * 5000, lastStrike: Date.now() + Math.random() * 3000 }); }
          } else {
            for (let i = 0; i < Math.max(5, baseSeasonalParticleCount * 0.1); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, size: 5 + Math.random() * 10, speed: 1 + Math.random() * 2, angle: Math.random() * Math.PI * 2, wingSpeed: 0.1 + Math.random() * 0.2, wingPhase: Math.random() * Math.PI * 2, color: ['#FFD700', '#FF6347', '#9370DB', '#20B2AA', '#FFB6C1'][Math.floor(Math.random() * 5)], type: 'butterfly' }); }
            for (let i = 0; i < Math.max(3, baseSeasonalParticleCount * 0.05); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, size: 3 + Math.random() * 5, speed: 0.7 + Math.random() * 1.5, angle: Math.random() * Math.PI * 2, color: '#FF3333', type: 'ladybug', spots: 3 + Math.floor(Math.random() * 4), wiggleSpeed: 0.005 + Math.random() * 0.01, wiggleAmount: 0.3 + Math.random() * 0.5, lastWiggle: Date.now() }); }
            for (let i = 0; i < baseSeasonalParticleCount * 0.15; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 0.5 + Math.random() * 1.5, d: Math.random() * Math.PI * 2, speed: 0.2 + Math.random() * 0.5, drift: 0.2 + Math.random() * 0.5, opacity: 0.3 + Math.random() * 0.4, color: '#FFFF99', type: 'pollen' }); }
            for (let i = 0; i < baseSeasonalParticleCount * 0.1; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 3 + Math.random() * 5, drift: 0.3 + Math.random() * 0.7, speed: 0.7 + Math.random() * 1.2, color: ['#FFB7C5', '#FF7BAC', '#FFDBF1', '#FFFFFF'][Math.floor(Math.random() * 4)], rotation: Math.random() * Math.PI * 2, rotationSpeed: (Math.random() - 0.5) * 0.02, type: 'petal' }); }
            if (Math.random() < 0.1) { createRainbowEffect(); }
          }
          break;
        case 5: 
          for (let i = 0; i < Math.max(10, baseSeasonalParticleCount * 0.2); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 1.5 + Math.random() * 3.5, opacity: 0.1 + Math.random() * 0.4, speed: 0.001 + Math.random() * 0.002, color: '#FFFFFF', type: 'sunflare' }); }
          for (let i = 0; i < Math.max(4, baseSeasonalParticleCount * 0.1); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, size: 6 + Math.random() * 12, speed: 1.2 + Math.random() * 2.2, angle: Math.random() * Math.PI * 2, wingSpeed: 0.12 + Math.random() * 0.22, wingPhase: Math.random() * Math.PI * 2, color: ['#FFD700', '#FF6347', '#9370DB', '#20B2AA', '#FFB6C1', '#87CEEB'][Math.floor(Math.random() * 6)], type: 'butterfly' }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.15; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 1 + Math.random() * 2, opacity: 0.6 + Math.random() * 0.4, speed: 0.3 + Math.random() * 0.6, drift: 0.5 + Math.random() * 1, type: 'dandelion', angle: Math.random() * Math.PI * 2 }); }
          break;
		case 6: 
		  for (let i = 0; i < Math.max(15, baseSeasonalParticleCount * 0.25); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 2 + Math.random() * 4, opacity: 0.15 + Math.random() * 0.45, speed: 0.001 + Math.random() * 0.0015, color: Math.random() > 0.7 ? '#FFFFCC' : '#FFFFFF', type: 'sunflare' }); } 
		  for (let i = 0; i < Math.min(3, Math.ceil(baseSeasonalParticleCount * 0.02)); i++) { seasonalParticles.push({ x: seasonalCanvasWidth * i / 3 - 150, y: Math.random() * seasonalCanvasHeight * 0.4, width: 120 + Math.random() * 180, height: 60 + Math.random() * 90, speed: 0.3 + Math.random() * 0.5, opacity: 0.6 + Math.random() * 0.4, type: 'cloud' }); }
		  for (let i = 0; i < Math.max(2, baseSeasonalParticleCount * 0.02); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight * 0.7, size: 10 + Math.random() * 10, speed: 2 + Math.random() * 3, angle: Math.random() * Math.PI * 2, wingSpeed: 0.3 + Math.random() * 0.4, wingPhase: Math.random() * Math.PI * 2, type: 'dragonfly' }); }
		  break;
        case 7: 
          for (let i = 0; i < Math.max(12, baseSeasonalParticleCount * 0.22); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 2 + Math.random() * 4, opacity: 0.12 + Math.random() * 0.4, speed: 0.0008 + Math.random() * 0.001, color: '#FFDD99', type: 'sunflare' }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.3; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: seasonalCanvasHeight - (Math.random() * seasonalCanvasHeight * 0.5), r: 30 + Math.random() * 50, opacity: 0.03 + Math.random() * 0.07, type: 'heat', speed: 0.1 + Math.random() * 0.15 }); }
          for (let i = 0; i < Math.max(2, baseSeasonalParticleCount * 0.04); i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight * 0.7, size: 8 + Math.random() * 8, speed: 2.5 + Math.random() * 3.5, angle: Math.random() * Math.PI * 2, wingSpeed: 0.35 + Math.random() * 0.45, wingPhase: Math.random() * Math.PI * 2, type: 'dragonfly' }); }
          break;
        case 8: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.3; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 5 + Math.random() * 10, rotation: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.5, drift: 0.5 + Math.random() * 1.2, rotationSpeed: (Math.random() - 0.5) * 0.02, color: ['#FFAA33', '#FFCC66', '#FF9900', '#FFBB33'][Math.floor(Math.random() * 4)], type: 'leaf', shape: Math.floor(Math.random() * 3) }); }
          break;
        case 9: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.8; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 5 + Math.random() * 12, rotation: Math.random() * Math.PI * 2, speed: 1 + Math.random() * 2, drift: 0.8 + Math.random() * 1.5, rotationSpeed: (Math.random() - 0.5) * 0.018, color: ['#8B4513', '#A0522D', '#CD853F', '#D2691E', '#F4A460', '#B8860B', '#DAA520'][Math.floor(Math.random() * 7)], type: 'leaf', shape: Math.floor(Math.random() * 4), swingFactor: 0.1 + Math.random() * 0.3 }); }
          break;
        case 10: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.4; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 4 + Math.random() * 10, rotation: Math.random() * Math.PI * 2, speed: 1.2 + Math.random() * 2.2, drift: 1 + Math.random() * 1.8, rotationSpeed: (Math.random() - 0.5) * 0.02, color: ['#805A46', '#7D4427', '#5C4033', '#8B5A2B', '#654321'][Math.floor(Math.random() * 5)], type: 'leaf', shape: Math.floor(Math.random() * 3), withered: true, swingFactor: 0.15 + Math.random() * 0.35 }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.8; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, length: 15 + Math.random() * 25, speed: 16 + Math.random() * 12, opacity: 0.3 + Math.random() * 0.3, type: 'rain' }); }
          for (let i = 0; i < baseSeasonalParticleCount * 0.4; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 40 + Math.random() * 80, opacity: 0.05 + Math.random() * 0.1, type: 'mist', speed: 0.05 + Math.random() * 0.15 }); }
          break;
        case 11: 
          for (let i = 0; i < baseSeasonalParticleCount * 0.9; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 2 + Math.random() * 4, d: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.7, drift: 0.6 + Math.random() * 1.7, opacity: 0.5 + Math.random() * 0.5, type: 'snow', arms: 6, detail: Math.random() > 0.5 }); }
          break;
        default: 
          for (let i = 0; i < baseSeasonalParticleCount; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 2 + Math.random() * 4, d: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.7, drift: 0.6 + Math.random() * 1.7, opacity: 0.5 + Math.random() * 0.5, type: 'snow', arms: 6, detail: Math.random() > 0.5 }); }
      }

    if (isCurrentlyNewYear) {
        seasonalParticles = seasonalParticles.filter(p => Math.random() < 0.1 && p.type === 'snow');
        for (let i = 0; i < baseSeasonalParticleCount * 0.4; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 3 + Math.random() * 5, d: Math.random() * Math.PI * 2, speed: 0.6 + Math.random() * 1.4, drift: 0.4 + Math.random() * 1.2, opacity: 0.7 + Math.random() * 0.3, type: 'snow', arms: 6 + Math.floor(Math.random() * 3) * 2, detail: true });}
        for (let i = 0; i < baseSeasonalParticleCount * 0.3; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 1 + Math.random() * 3, opacity: 0.4 + Math.random() * 0.6, color: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff', '#00ffff', '#ffffff'][Math.floor(Math.random() * 7)], type: 'twinkle', speed: 0.001 + Math.random() * 0.002, twinkleSpeed: 0.03 + Math.random() * 0.06 });}
        for (let i = 0; i < baseSeasonalParticleCount * 0.3; i++) { seasonalParticles.push({ x: Math.random() * seasonalCanvasWidth, y: Math.random() * seasonalCanvasHeight, r: 2 + Math.random() * 4, rotation: Math.random() * Math.PI * 2, speed: 1 + Math.random() * 3, drift: 0.5 + Math.random() * 1.5, rotationSpeed: (Math.random() - 0.5) * 0.05, color: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff', '#00ffff', '#ffffff', '#ff9900'][Math.floor(Math.random() * 8)], type: 'confetti', shape: Math.floor(Math.random() * 3) });}
    }
}

function createRainbowEffect() {
    seasonalParticles = seasonalParticles.filter(p => p.type !== 'rainbow');
    seasonalParticles.push({ type: 'rainbow', opacity: 0, fadeIn: true, fadeSpeed: 0.01, maxOpacity: 0.6, width: seasonalCanvasWidth * 1.5, creationTime: Date.now() });
}

function updateAndDrawSeasonalParticles() {
    if (!seasonalCtx || !seasonalCanvas) return;
    seasonalCtx.clearRect(0, 0, seasonalCanvasWidth, seasonalCanvasHeight);
    const currentTime = Date.now();

    if (seasonalParticles.length < baseSeasonalParticleCount * 0.8 && currentTime - lastParticleTime > PARTICLE_SETTINGS.CREATION_INTERVAL) {
        addNewSeasonalParticles();
        lastParticleTime = currentTime;
    }

    for (let i = seasonalParticles.length - 1; i >= 0; i--) {
        const p = seasonalParticles[i];
        let particleRemoved = false;

        switch (p.type) {
            case 'snow': drawSnow(p); if (p.melting && (p.r < 0.5 || p.opacity < 0.1)) { seasonalParticles.splice(i, 1); particleRemoved = true; } break;
            case 'rain': drawRain(p); break;
            case 'petal': drawPetal(p); break;
            case 'sunflare': drawSunflare(p); break;
            case 'butterfly': drawButterfly(p); break;
            case 'dragonfly': drawDragonfly(p); break;
            case 'leaf': drawLeaf(p); break;
            case 'mist': drawMist(p); break;
            case 'cloud': drawCloud(p); break;
            case 'pollen': drawPollen(p); break;
            case 'heat': drawHeat(p); break;
            case 'dandelion': drawDandelion(p); break;
            case 'twinkle': drawTwinkle(p); break;
            case 'confetti': drawConfetti(p); break;
            case 'rainbow':
                drawRainbow(p);
                if (!p.fadeIn && currentTime - p.creationTime > 15000) { p.fadeOut = true; }
                if (p.fadeOut) { p.opacity -= p.fadeSpeed * 2; if (p.opacity <= 0) { seasonalParticles.splice(i, 1); particleRemoved = true; }}
                break;
            case 'ladybug': drawLadybug(p); break;
            case 'bud': drawBud(p); break;
            case 'lightning':
                drawLightning(p);
                if (p.opacity <= 0 && !p.hasOwnProperty('nextStrike')) { seasonalParticles.splice(i, 1); particleRemoved = true; }
                else if (p.opacity <= 0 && p.hasOwnProperty('nextStrike')) {
                    if (Date.now() - p.lastStrike > p.nextStrike) { p.opacity = 0.9; p.x = Math.random() * seasonalCanvasWidth; p.y = 0; p.lastStrike = Date.now(); p.nextStrike = 3000 + Math.random() * 6000; }
                }
                break;
            default: seasonalParticles.splice(i, 1); particleRemoved = true; break;
        }

        if (!particleRemoved && !p.hasOwnProperty('nextStrike') &&
            (p.y > seasonalCanvasHeight + (p.r || p.length || p.size || 50) * 2 ||
             p.y < -(p.r || p.length || p.size || 50) * 2 ||
             p.x > seasonalCanvasWidth + (p.r || p.size || 50) * 2 ||
             p.x < -(p.r || p.size || 50) * 2)) {
            seasonalParticles.splice(i, 1);
        }
    }
}

function addNewSeasonalParticles() {
    const date = getCurrentDateInternal();
    const month = date.getMonth();
    const day = date.getDate();
    const isCurrentlyNewYear = (month === 11 && day === 31) || (month === 0 && day === 1);
    const countToAdd = Math.max(1, Math.floor(baseSeasonalParticleCount * 0.05));

    for (let i = 0; i < countToAdd; i++) {
        let newParticle = null;
        const randomTypeChoice = Math.random();

        switch (month) {
            case 0: newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 2 + Math.random() * 4, d: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.6, drift: 0.6 + Math.random() * 1.6, opacity: 0.6 + Math.random() * 0.4, type: 'snow', arms: 6 + Math.floor(Math.random() * 2) * 2, detail: Math.random() > 0.7 }; break;
            case 1: newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 1.5 + Math.random() * 3, d: Math.random() * Math.PI * 2, speed: 2 + Math.random() * 4, drift: 2 + Math.random() * 3, opacity: 0.4 + Math.random() * 0.6, type: 'snow', turbulence: 0.3 + Math.random() * 0.7, arms: 5 + Math.floor(Math.random() * 3), detail: false }; break;
            case 2: newParticle = (randomTypeChoice < 0.7) ? { x: Math.random() * seasonalCanvasWidth, y: -20, length: 8 + Math.random() * 15, speed: 12 + Math.random() * 8, opacity: 0.2 + Math.random() * 0.3, type: 'rain' } : { x: Math.random() * seasonalCanvasWidth, y: -10, r: 1 + Math.random() * 2, d: Math.random() * Math.PI * 2, speed: 1 + Math.random() * 2, drift: 0.2 + Math.random() * 0.8, opacity: 0.3 + Math.random() * 0.3, type: 'snow', melting: true, arms: 6 }; break;
            case 3:
                if (randomTypeChoice < 0.5) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -20, length: 6 + Math.random() * 12, speed: 10 + Math.random() * 6, opacity: 0.15 + Math.random() * 0.2, type: 'rain' }; }
                else if (randomTypeChoice < 0.8) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 3 + Math.random() * 5, drift: 0.3 + Math.random() * 0.7, speed: 0.7 + Math.random() * 1.2, color: ['#FFB7C5', '#FF7BAC', '#FFC0CB', '#FFDBF1', '#ffffff'][Math.floor(Math.random() * 5)], rotation: Math.random() * Math.PI * 2, rotationSpeed: (Math.random() - 0.5) * 0.02, type: 'petal' }; }
                else { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 1 + Math.random() * 1.5, color: '#90EE90', opacity: 0.6 + Math.random() * 0.3, speed: 0.1 + Math.random() * 0.3, drift: 0.1 + Math.random() * 0.3, type: 'bud' }; }
                break;
            case 4:
              const isRainingMay = seasonalParticles.some(p => p.type === 'rain');
              if (isRainingMay) { if (randomTypeChoice < 0.8) newParticle = { x: Math.random() * seasonalCanvasWidth, y: -20, length: 15 + Math.random() * 25, speed: 20 + Math.random() * 15, opacity: 0.3 + Math.random() * 0.3, type: 'rain' };}
              else {
                 if (randomTypeChoice < 0.3) newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, size: 5 + Math.random() * 10, speed: 1 + Math.random() * 2, angle: Math.random() * Math.PI * 2, wingSpeed: 0.1 + Math.random() * 0.2, wingPhase: Math.random() * Math.PI * 2, color: ['#FFD700', '#FF6347', '#9370DB', '#20B2AA', '#FFB6C1'][Math.floor(Math.random() * 5)], type: 'butterfly' };
                 else if (randomTypeChoice < 0.5) newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, size: 3 + Math.random() * 5, speed: 0.7 + Math.random() * 1.5, angle: Math.random() * Math.PI * 2, color: '#FF3333', type: 'ladybug', spots: 3 + Math.floor(Math.random() * 4), wiggleSpeed: 0.005 + Math.random() * 0.01, wiggleAmount: 0.3 + Math.random() * 0.5, lastWiggle: Date.now() };
                 else if (randomTypeChoice < 0.8) newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 0.5 + Math.random() * 1.5, d: Math.random() * Math.PI * 2, speed: 0.2 + Math.random() * 0.5, drift: 0.2 + Math.random() * 0.5, opacity: 0.3 + Math.random() * 0.4, color: '#FFFF99', type: 'pollen' };
                 else newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 3 + Math.random() * 5, drift: 0.3 + Math.random() * 0.7, speed: 0.7 + Math.random() * 1.2, color: ['#FFB7C5', '#FF7BAC', '#FFDBF1', '#FFFFFF'][Math.floor(Math.random() * 4)], rotation: Math.random() * Math.PI * 2, rotationSpeed: (Math.random() - 0.5) * 0.02, type: 'petal' };
              }
              break;
            case 5:
              if (randomTypeChoice < 0.3) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 1.5 + Math.random() * 3.5, opacity: 0.1 + Math.random() * 0.4, speed: 0.001 + Math.random() * 0.002, color: '#FFFFFF', type: 'sunflare' }; }
              else if (randomTypeChoice < 0.7) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, size: 6 + Math.random() * 12, speed: 1.2 + Math.random() * 2.2, angle: Math.random() * Math.PI * 2, wingSpeed: 0.12 + Math.random() * 0.22, wingPhase: Math.random() * Math.PI * 2, color: ['#FFD700', '#FF6347', '#9370DB', '#20B2AA', '#FFB6C1', '#87CEEB'][Math.floor(Math.random() * 6)], type: 'butterfly' }; }
              else { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 1 + Math.random() * 2, opacity: 0.6 + Math.random() * 0.4, speed: 0.3 + Math.random() * 0.6, drift: 0.5 + Math.random() * 1, type: 'dandelion', angle: Math.random() * Math.PI * 2 }; }
              break;
			case 6:
			  const cloudCount = seasonalParticles.filter(p => p.type === 'cloud').length;
			  if (randomTypeChoice < 0.6) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 2 + Math.random() * 4, opacity: 0.15 + Math.random() * 0.45, speed: 0.001 + Math.random() * 0.0015, color: Math.random() > 0.7 ? '#FFFFCC' : '#FFFFFF', type: 'sunflare' }; }
              else if (randomTypeChoice < 0.85 && cloudCount < 3) { newParticle = { x: -100, y: Math.random() * seasonalCanvasHeight * 0.4, width: 120 + Math.random() * 180, height: 60 + Math.random() * 90, speed: 0.3 + Math.random() * 0.5, opacity: 0.6 + Math.random() * 0.4, type: 'cloud' }; }
              else { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, size: 10 + Math.random() * 10, speed: 2 + Math.random() * 3, angle: Math.random() * Math.PI * 2, wingSpeed: 0.3 + Math.random() * 0.4, wingPhase: Math.random() * Math.PI * 2, type: 'dragonfly' }; }
			  break;
            case 7:
              if (randomTypeChoice < 0.4) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 2 + Math.random() * 4, opacity: 0.12 + Math.random() * 0.4, speed: 0.0008 + Math.random() * 0.001, color: '#FFDD99', type: 'sunflare' }; }
              else if (randomTypeChoice < 0.7) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: seasonalCanvasHeight, r: 30 + Math.random() * 50, opacity: 0.03 + Math.random() * 0.07, type: 'heat', speed: 0.1 + Math.random() * 0.15 }; }
              else { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, size: 8 + Math.random() * 8, speed: 2.5 + Math.random() * 3.5, angle: Math.random() * Math.PI * 2, wingSpeed: 0.35 + Math.random() * 0.45, wingPhase: Math.random() * Math.PI * 2, type: 'dragonfly' }; }
              break;
            case 8: newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 5 + Math.random() * 10, rotation: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.5, drift: 0.5 + Math.random() * 1.2, rotationSpeed: (Math.random() - 0.5) * 0.02, color: ['#FFAA33', '#FFCC66', '#FF9900', '#FFBB33'][Math.floor(Math.random() * 4)], type: 'leaf', shape: Math.floor(Math.random() * 3) }; break;
            case 9: newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 5 + Math.random() * 12, rotation: Math.random() * Math.PI * 2, speed: 1 + Math.random() * 2, drift: 0.8 + Math.random() * 1.5, rotationSpeed: (Math.random() - 0.5) * 0.018, color: ['#8B4513', '#A0522D', '#CD853F', '#D2691E', '#F4A460', '#B8860B', '#DAA520'][Math.floor(Math.random() * 7)], type: 'leaf', shape: Math.floor(Math.random() * 4), swingFactor: 0.1 + Math.random() * 0.3 }; break;
            case 10:
              if (randomTypeChoice < 0.3) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 4 + Math.random() * 10, rotation: Math.random() * Math.PI * 2, speed: 1.2 + Math.random() * 2.2, drift: 1 + Math.random() * 1.8, rotationSpeed: (Math.random() - 0.5) * 0.02, color: ['#805A46', '#7D4427', '#5C4033', '#8B5A2B', '#654321'][Math.floor(Math.random() * 5)], type: 'leaf', shape: Math.floor(Math.random() * 3), withered: true, swingFactor: 0.15 + Math.random() * 0.35 }; }
              else if (randomTypeChoice < 0.8) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -20, length: 15 + Math.random() * 25, speed: 16 + Math.random() * 12, opacity: 0.3 + Math.random() * 0.3, type: 'rain' }; }
              else { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 40 + Math.random() * 80, opacity: 0.05 + Math.random() * 0.1, type: 'mist', speed: 0.05 + Math.random() * 0.15 }; }
              break;
            case 11: newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 2 + Math.random() * 4, d: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.7, drift: 0.6 + Math.random() * 1.7, opacity: 0.5 + Math.random() * 0.5, type: 'snow', arms: 6, detail: Math.random() > 0.5 }; break;
            default: newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 2 + Math.random() * 4, d: Math.random() * Math.PI * 2, speed: 0.8 + Math.random() * 1.7, drift: 0.6 + Math.random() * 1.7, opacity: 0.5 + Math.random() * 0.5, type: 'snow', arms: 6, detail: Math.random() > 0.5 };
        }

        if (isCurrentlyNewYear) {
            const nyChoice = Math.random();
            if (nyChoice < 0.4) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 3 + Math.random() * 5, d: Math.random() * Math.PI * 2, speed: 0.6 + Math.random() * 1.4, drift: 0.4 + Math.random() * 1.2, opacity: 0.7 + Math.random() * 0.3, type: 'snow', arms: 6 + Math.floor(Math.random() * 3) * 2, detail: true }; }
            else if (nyChoice < 0.7) { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 1 + Math.random() * 3, opacity: 0.4 + Math.random() * 0.6, color: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff', '#00ffff', '#ffffff'][Math.floor(Math.random() * 7)], type: 'twinkle', speed: 0.001 + Math.random() * 0.002, twinkleSpeed: 0.03 + Math.random() * 0.06 }; }
            else { newParticle = { x: Math.random() * seasonalCanvasWidth, y: -10, r: 2 + Math.random() * 4, rotation: Math.random() * Math.PI * 2, speed: 1 + Math.random() * 3, drift: 0.5 + Math.random() * 1.5, rotationSpeed: (Math.random() - 0.5) * 0.05, color: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff', '#00ffff', '#ffffff', '#ff9900'][Math.floor(Math.random() * 8)], type: 'confetti', shape: Math.floor(Math.random() * 3) }; }
        }

        if (newParticle && seasonalParticles.length < baseSeasonalParticleCount * 1.2) {
            seasonalParticles.push(newParticle);
        }
    }
}

// --- Функции отрисовки разных типов сезонных частиц ---
// Эти функции используют seasonalCtx, seasonalCanvasWidth, seasonalCanvasHeight
function drawSnow(p) { seasonalCtx.save(); seasonalCtx.globalAlpha = p.opacity; if (p.detail) { seasonalCtx.beginPath(); const armLength = p.r; for (let i = 0; i < p.arms; i++) { const angle = (Math.PI * 2 / p.arms) * i; const x1 = p.x + Math.cos(angle) * armLength; const y1 = p.y + Math.sin(angle) * armLength; seasonalCtx.moveTo(p.x, p.y); seasonalCtx.lineTo(x1, y1); if (p.arms <= 6) { const branchLength = armLength * 0.4; const branchAngle1 = angle + Math.PI / 4; const branchAngle2 = angle - Math.PI / 4; const midX = p.x + Math.cos(angle) * (armLength * 0.5); const midY = p.y + Math.sin(angle) * (armLength * 0.5); const branchX1 = midX + Math.cos(branchAngle1) * branchLength; const branchY1 = midY + Math.sin(branchAngle1) * branchLength; const branchX2 = midX + Math.cos(branchAngle2) * branchLength; const branchY2 = midY + Math.sin(branchAngle2) * branchLength; seasonalCtx.moveTo(midX, midY); seasonalCtx.lineTo(branchX1, branchY1); seasonalCtx.moveTo(midX, midY); seasonalCtx.lineTo(branchX2, branchY2); } } seasonalCtx.strokeStyle = '#fff'; seasonalCtx.lineWidth = p.r * 0.1; seasonalCtx.stroke(); } else { seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r, 0, Math.PI * 2); seasonalCtx.fillStyle = '#fff'; seasonalCtx.fill(); } if (p.turbulence) { seasonalCtx.shadowBlur = 3; seasonalCtx.shadowColor = '#fff'; } seasonalCtx.restore(); if (p.turbulence) { p.d += (Math.random() - 0.5) * p.turbulence; } p.y += p.speed; p.x += Math.sin(p.d) * p.drift; p.d += 0.01 + Math.random() * 0.01; if (p.y > seasonalCanvasHeight + p.r) { p.y = -p.r; p.x = Math.random() * seasonalCanvasWidth; } if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; if (p.melting && Math.random() < 0.03) { p.r *= 0.95; p.opacity *= 0.95; } }
function drawRain(p) { seasonalCtx.save(); seasonalCtx.beginPath(); seasonalCtx.moveTo(p.x, p.y); seasonalCtx.lineTo(p.x, p.y + p.length); seasonalCtx.strokeStyle = `rgba(200, 200, 255, ${p.opacity})`; seasonalCtx.lineWidth = 1; seasonalCtx.stroke(); seasonalCtx.restore(); p.y += p.speed; if (p.y > seasonalCanvasHeight) { p.y = -p.length; p.x = Math.random() * seasonalCanvasWidth; } }
function drawPetal(p) { seasonalCtx.save(); seasonalCtx.translate(p.x, p.y); seasonalCtx.rotate(p.rotation); seasonalCtx.beginPath(); seasonalCtx.ellipse(0, 0, p.r * 0.6, p.r, 0, 0, Math.PI * 2); seasonalCtx.fillStyle = p.color; seasonalCtx.globalAlpha = 0.8; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.moveTo(-p.r * 0.4, 0); seasonalCtx.lineTo(p.r * 0.4, 0); seasonalCtx.strokeStyle = 'rgba(255, 255, 255, 0.3)'; seasonalCtx.lineWidth = 0.5; seasonalCtx.stroke(); seasonalCtx.restore(); p.y += p.speed; p.x += Math.sin(p.rotation * 2 + p.y * 0.05) * p.drift; p.rotation += p.rotationSpeed; if (p.y > seasonalCanvasHeight + p.r) { p.y = -p.r; p.x = Math.random() * seasonalCanvasWidth; } if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; }
function drawSunflare(p) { seasonalCtx.save(); const flicker = Math.sin(Date.now() * p.speed + p.x) * 0.5 + 0.5; seasonalCtx.globalAlpha = p.opacity * flicker; const gradient = seasonalCtx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r); gradient.addColorStop(0, p.color || 'rgba(255, 255, 200, 1)'); gradient.addColorStop(1, 'rgba(255, 255, 200, 0)'); seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r, 0, Math.PI * 2); seasonalCtx.fillStyle = gradient; seasonalCtx.shadowColor = p.color || 'rgba(255, 255, 200, 0.8)'; seasonalCtx.shadowBlur = 10; seasonalCtx.fill(); seasonalCtx.restore(); p.x += (Math.random() - 0.5) * 0.3; p.y += (Math.random() - 0.5) * 0.3; if (p.y > seasonalCanvasHeight + p.r) p.y = -p.r; if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; if (p.y < -p.r) p.y = seasonalCanvasHeight + p.r; }
function drawButterfly(p) { const wingOpen = Math.sin(Date.now() * p.wingSpeed + p.wingPhase) * 0.5 + 0.5; seasonalCtx.save(); seasonalCtx.translate(p.x, p.y); seasonalCtx.rotate(p.angle + Math.PI / 2); seasonalCtx.fillStyle = p.color; seasonalCtx.beginPath(); seasonalCtx.moveTo(0, -p.size * 0.7); seasonalCtx.bezierCurveTo(-p.size * 1.5 * wingOpen, -p.size * 1.2, -p.size * 1.5 * wingOpen, p.size * 0.8, 0, p.size * 0.3); seasonalCtx.moveTo(0, -p.size * 0.7); seasonalCtx.bezierCurveTo(p.size * 1.5 * wingOpen, -p.size * 1.2, p.size * 1.5 * wingOpen, p.size * 0.8, 0, p.size * 0.3); seasonalCtx.fillStyle = p.color; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.arc(-p.size * 0.8 * wingOpen, -p.size * 0.3, p.size * 0.25, 0, Math.PI * 2); seasonalCtx.arc(p.size * 0.8 * wingOpen, -p.size * 0.3, p.size * 0.25, 0, Math.PI * 2); seasonalCtx.fillStyle = 'rgba(255, 255, 255, 0.6)'; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.ellipse(0, 0, p.size / 4, p.size * 0.8, 0, 0, Math.PI * 2); seasonalCtx.fillStyle = '#333'; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.moveTo(0, -p.size * 0.7); seasonalCtx.lineTo(-p.size * 0.3, -p.size * 1); seasonalCtx.moveTo(0, -p.size * 0.7); seasonalCtx.lineTo(p.size * 0.3, -p.size * 1); seasonalCtx.strokeStyle = '#333'; seasonalCtx.lineWidth = 1; seasonalCtx.stroke(); seasonalCtx.restore(); p.x += Math.cos(p.angle) * p.speed; p.y += Math.sin(p.angle) * p.speed; if (Math.random() < 0.05) { p.angle += (Math.random() - 0.5) * Math.PI / 4; } if (p.x < p.size * 2 || p.x > seasonalCanvasWidth - p.size * 2) { p.angle = Math.PI - p.angle + (Math.random() - 0.5) * 0.2; p.x = Math.max(p.size * 2, Math.min(seasonalCanvasWidth - p.size * 2, p.x)); } if (p.y < p.size * 2 || p.y > seasonalCanvasHeight - p.size * 2) { p.angle = -p.angle + (Math.random() - 0.5) * 0.2; p.y = Math.max(p.size * 2, Math.min(seasonalCanvasHeight - p.size * 2, p.y)); } }
function drawDragonfly(p) { const wingBeat = Math.sin(Date.now() * p.wingSpeed + p.wingPhase); seasonalCtx.save(); seasonalCtx.translate(p.x, p.y); seasonalCtx.rotate(p.angle + Math.PI / 2); const bodyGradient = seasonalCtx.createLinearGradient(0, -p.size, 0, p.size); bodyGradient.addColorStop(0, '#45CFFF'); bodyGradient.addColorStop(0.3, '#5DA4FF'); bodyGradient.addColorStop(0.7, '#4580FF'); bodyGradient.addColorStop(1, '#45CFFF'); seasonalCtx.beginPath(); seasonalCtx.ellipse(0, 0, p.size/7, p.size, 0, 0, Math.PI * 2); seasonalCtx.fillStyle = bodyGradient; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.arc(0, -p.size * 0.8, p.size/5, 0, Math.PI * 2); seasonalCtx.fillStyle = '#5DA4FF'; seasonalCtx.fill(); seasonalCtx.globalAlpha = 0.25; const wingAngle = Math.PI/5 * wingBeat; const wingGradient = seasonalCtx.createLinearGradient(-p.size, 0, p.size, 0); wingGradient.addColorStop(0, 'rgba(200, 240, 255, 0.9)'); wingGradient.addColorStop(0.5, 'rgba(255, 255, 255, 0.9)'); wingGradient.addColorStop(1, 'rgba(200, 240, 255, 0.9)'); seasonalCtx.beginPath(); seasonalCtx.ellipse(-p.size * 0.6, -p.size * 0.3, p.size * 0.5, p.size * 0.15, wingAngle, 0, Math.PI * 2); seasonalCtx.ellipse(p.size * 0.6, -p.size * 0.3, p.size * 0.5, p.size * 0.15, -wingAngle, 0, Math.PI * 2); seasonalCtx.ellipse(-p.size * 0.5, p.size * 0.1, p.size * 0.4, p.size * 0.12, wingAngle * 0.8, 0, Math.PI * 2); seasonalCtx.ellipse(p.size * 0.5, p.size * 0.1, p.size * 0.4, p.size * 0.12, -wingAngle * 0.8, 0, Math.PI * 2); seasonalCtx.fillStyle = wingGradient; seasonalCtx.fill(); seasonalCtx.globalAlpha = 0.15; seasonalCtx.beginPath(); seasonalCtx.moveTo(-p.size * 0.6, -p.size * 0.3); seasonalCtx.lineTo(-p.size * 1.1, -p.size * 0.4); seasonalCtx.moveTo(p.size * 0.6, -p.size * 0.3); seasonalCtx.lineTo(p.size * 1.1, -p.size * 0.4); seasonalCtx.moveTo(-p.size * 0.5, p.size * 0.1); seasonalCtx.lineTo(-p.size * 0.9, p.size * 0.2); seasonalCtx.moveTo(p.size * 0.5, p.size * 0.1); seasonalCtx.lineTo(p.size * 0.9, p.size * 0.2); seasonalCtx.strokeStyle = '#ffffff'; seasonalCtx.lineWidth = 1; seasonalCtx.stroke(); seasonalCtx.restore(); p.x += Math.cos(p.angle) * p.speed; p.y += Math.sin(p.angle) * p.speed; if (Math.random() < 0.02) { p.angle += (Math.random() - 0.5) * Math.PI / 2; } if (p.x < p.size || p.x > seasonalCanvasWidth - p.size) { p.angle = Math.PI - p.angle; p.x = Math.max(p.size, Math.min(seasonalCanvasWidth - p.size, p.x)); } if (p.y < p.size || p.y > seasonalCanvasHeight - p.size) { p.angle = -p.angle; p.y = Math.max(p.size, Math.min(seasonalCanvasHeight - p.size, p.y)); } }
function drawLeaf(p) { seasonalCtx.save(); seasonalCtx.translate(p.x, p.y); seasonalCtx.rotate(p.rotation); seasonalCtx.beginPath(); seasonalCtx.moveTo(0, -p.r * 1.2); seasonalCtx.bezierCurveTo(p.r * 0.8, -p.r * 0.5, p.r * 0.7, p.r * 0.5, 0, p.r); seasonalCtx.bezierCurveTo(-p.r * 0.7, p.r * 0.5, -p.r * 0.8, -p.r * 0.5, 0, -p.r * 1.2); seasonalCtx.fillStyle = p.color; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.moveTo(0, -p.r * 1.1); seasonalCtx.lineTo(0, p.r * 0.9); seasonalCtx.strokeStyle = 'rgba(0, 0, 0, 0.3)'; seasonalCtx.lineWidth = p.r * 0.05; seasonalCtx.stroke(); seasonalCtx.beginPath(); const veinsCount = 5; for (let i = 0; i < veinsCount; i++) { const yPos = -p.r + i * (2 * p.r) / (veinsCount - 1); const veinLength = p.r * 0.5 * (1 - Math.abs(yPos) / p.r); seasonalCtx.moveTo(0, yPos); seasonalCtx.lineTo(veinLength, yPos + veinLength * 0.2); seasonalCtx.moveTo(0, yPos); seasonalCtx.lineTo(-veinLength, yPos + veinLength * 0.2); } seasonalCtx.strokeStyle = 'rgba(0, 0, 0, 0.2)'; seasonalCtx.lineWidth = p.r * 0.03; seasonalCtx.stroke(); if (p.withered) { seasonalCtx.globalCompositeOperation = 'source-atop'; seasonalCtx.fillStyle = 'rgba(100, 60, 30, 0.4)'; seasonalCtx.fill(); seasonalCtx.globalCompositeOperation = 'source-over'; seasonalCtx.beginPath(); seasonalCtx.moveTo(-p.r * 0.5, p.r * 0.3); seasonalCtx.quadraticCurveTo(0, p.r * 0.5, p.r * 0.5, p.r * 0.2); seasonalCtx.strokeStyle = 'rgba(100, 60, 30, 0.4)'; seasonalCtx.lineWidth = 1; seasonalCtx.stroke(); } seasonalCtx.restore(); p.y += p.speed; if (p.swingFactor) { const swingAmount = p.swingFactor * Math.sin(p.y * 0.03); p.x += swingAmount * p.drift; } else { p.x += Math.sin(p.rotation * 3) * p.drift; } p.rotation += p.rotationSpeed; if (p.y > seasonalCanvasHeight + p.r * 2) { p.y = -p.r * 2; p.x = Math.random() * seasonalCanvasWidth; p.speed = p.speed * (0.9 + Math.random() * 0.2); p.drift = p.drift * (0.9 + Math.random() * 0.2); p.rotationSpeed = p.rotationSpeed * (0.9 + Math.random() * 0.2); } if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; }
function drawMist(p) { seasonalCtx.save(); const gradient = seasonalCtx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r); gradient.addColorStop(0, `rgba(200, 200, 210, ${p.opacity})`); gradient.addColorStop(1, 'rgba(200, 200, 210, 0)'); seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r, 0, Math.PI * 2); seasonalCtx.fillStyle = gradient; seasonalCtx.globalCompositeOperation = 'lighter'; seasonalCtx.fill(); seasonalCtx.restore(); p.x += (Math.random() - 0.5) * p.speed; p.y += (Math.random() - 0.5) * p.speed * 0.5; if (Math.random() < 0.01) { p.r = p.r * (0.95 + Math.random() * 0.1); } if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; if (p.y > seasonalCanvasHeight + p.r) p.y = -p.r; if (p.y < -p.r) p.y = seasonalCanvasHeight + p.r; }
function drawCloud(p) { seasonalCtx.save(); let cloudColor = p.isThunder ? `rgba(180, 180, 200, ${p.opacity})` : `rgba(255, 255, 255, ${p.opacity})`; seasonalCtx.fillStyle = cloudColor; seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.width * 0.4, 0, Math.PI * 2); seasonalCtx.arc(p.x + p.width * 0.2, p.y - p.height * 0.1, p.width * 0.3, 0, Math.PI * 2); seasonalCtx.arc(p.x + p.width * 0.4, p.y, p.width * 0.3, 0, Math.PI * 2); seasonalCtx.arc(p.x - p.width * 0.2, p.y + p.height * 0.1, p.width * 0.25, 0, Math.PI * 2); seasonalCtx.arc(p.x + p.width * 0.2, p.y + p.height * 0.1, p.width * 0.3, 0, Math.PI * 2); seasonalCtx.fill(); if (p.isThunder) { seasonalCtx.fillStyle = 'rgba(100, 100, 120, 0.2)'; seasonalCtx.beginPath(); seasonalCtx.ellipse(p.x, p.y + p.height * 0.2, p.width * 0.5, p.height * 0.3, 0, 0, Math.PI * 2); seasonalCtx.fill(); } seasonalCtx.restore(); p.x += p.speed; if (p.x > seasonalCanvasWidth + p.width) { p.x = -p.width; p.y = Math.random() * seasonalCanvasHeight * 0.4; } }
function drawPollen(p) { seasonalCtx.save(); seasonalCtx.globalAlpha = p.opacity; seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r, 0, Math.PI * 2); seasonalCtx.fillStyle = p.color; seasonalCtx.fill(); seasonalCtx.restore(); p.y += Math.sin(Date.now() * 0.001 + p.x) * 0.1; p.x += Math.cos(Date.now() * 0.001 + p.y) * 0.1 + p.drift; if (p.y > seasonalCanvasHeight + p.r) p.y = -p.r; if (p.y < -p.r) p.y = seasonalCanvasHeight + p.r; if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; }
function drawHeat(p) { seasonalCtx.save(); const gradient = seasonalCtx.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r); gradient.addColorStop(0, `rgba(255, 255, 255, ${p.opacity})`); gradient.addColorStop(1, 'rgba(255, 255, 255, 0)'); seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r, 0, Math.PI * 2); seasonalCtx.fillStyle = gradient; seasonalCtx.globalCompositeOperation = 'difference'; seasonalCtx.fill(); seasonalCtx.restore(); p.y -= p.speed; p.x += Math.sin(Date.now() * 0.001 + p.y * 0.1) * 0.3; if (p.y < -p.r) { p.y = seasonalCanvasHeight + p.r; p.x = Math.random() * seasonalCanvasWidth; } }
function drawLightning(p) { seasonalCtx.save(); seasonalCtx.strokeStyle = `rgba(255, 255, 255, ${p.opacity})`; seasonalCtx.lineWidth = 2 + Math.random() * 3; seasonalCtx.shadowColor = '#CCFFFF'; seasonalCtx.shadowBlur = 20; seasonalCtx.beginPath(); let x = p.x; let y = p.y; seasonalCtx.moveTo(x, y); const segments = 7 + Math.floor(Math.random() * 5); const maxDeviation = 40; for (let i = 0; i < segments; i++) { const targetY = seasonalCanvasHeight; const nextY = y + (targetY - p.y) / segments * (i + 1); const nextX = x + (Math.random() - 0.5) * maxDeviation; if (i > 0 && i < segments - 1 && Math.random() < 0.5) { const midX = (x + nextX) / 2 + (Math.random() - 0.5) * maxDeviation * 0.5; const midY = (y + nextY) / 2; seasonalCtx.lineTo(midX, midY); } seasonalCtx.lineTo(nextX, nextY); x = nextX; y = nextY; } seasonalCtx.stroke(); if (Math.random() < 0.6) { const branchStartSegment = Math.floor(Math.random() * (segments - 2)) + 1; const startY = p.y + (seasonalCanvasHeight - p.y) / segments * branchStartSegment; let startX = p.x; let tempX = p.x, tempY = p.y; for(let k=0; k < branchStartSegment; k++){ tempX += (Math.random() - 0.5)*maxDeviation; } startX = tempX; seasonalCtx.beginPath(); seasonalCtx.moveTo(startX, startY); let branchX = startX; let branchY = startY; const branchSegments = 2 + Math.floor(Math.random() * 3); for (let i = 0; i < branchSegments; i++) { branchX += (Math.random() - 0.3) * maxDeviation * 0.8; branchY += (seasonalCanvasHeight - startY) / (segments * 1.5); seasonalCtx.lineTo(branchX, branchY); } seasonalCtx.lineWidth = seasonalCtx.lineWidth * 0.7; seasonalCtx.stroke(); } seasonalCtx.restore(); if (p.opacity > 0.8) { seasonalCtx.save(); seasonalCtx.fillStyle = `rgba(200, 230, 255, ${p.opacity * 0.2})`; seasonalCtx.globalCompositeOperation = 'lighter'; seasonalCtx.fillRect(0, 0, seasonalCanvasWidth, seasonalCanvasHeight); seasonalCtx.restore(); } p.opacity -= 0.05 + Math.random() * 0.05; }
function drawLadybug(p) { seasonalCtx.save(); seasonalCtx.translate(p.x, p.y); seasonalCtx.rotate(p.angle + Math.PI / 2); seasonalCtx.beginPath(); seasonalCtx.arc(0, 0, p.size, 0, Math.PI * 2); seasonalCtx.fillStyle = p.color; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.arc(0, -p.size * 0.7, p.size * 0.5, 0, Math.PI * 2); seasonalCtx.fillStyle = '#000000'; seasonalCtx.fill(); seasonalCtx.beginPath(); seasonalCtx.moveTo(0, -p.size * 0.5); seasonalCtx.lineTo(0, p.size * 0.8); seasonalCtx.strokeStyle = '#000000'; seasonalCtx.lineWidth = 1; seasonalCtx.stroke(); seasonalCtx.fillStyle = '#000000'; const spotPositions = [ [-p.size * 0.4, -p.size * 0.3], [p.size * 0.4, -p.size * 0.3], [-p.size * 0.5, 0], [p.size * 0.5, 0], [-p.size * 0.3, p.size * 0.3], [p.size * 0.3, p.size * 0.3] ]; for (let i = 0; i < Math.min(p.spots, spotPositions.length); i++) { seasonalCtx.beginPath(); seasonalCtx.arc(spotPositions[i][0], spotPositions[i][1], p.size * 0.2, 0, Math.PI * 2); seasonalCtx.fill(); } seasonalCtx.restore(); const now = Date.now(); const elapsed = now - p.lastWiggle; const wiggle = Math.sin(elapsed * p.wiggleSpeed) * p.wiggleAmount; p.x += Math.cos(p.angle + wiggle) * p.speed; p.y += Math.sin(p.angle + wiggle) * p.speed; if (Math.random() < 0.02) { p.angle += (Math.random() - 0.5) * Math.PI / 4; } if (p.x < p.size || p.x > seasonalCanvasWidth - p.size) { p.angle = Math.PI - p.angle; p.x = Math.max(p.size, Math.min(seasonalCanvasWidth - p.size, p.x)); } if (p.y < p.size || p.y > seasonalCanvasHeight - p.size) { p.angle = -p.angle; p.y = Math.max(p.size, Math.min(seasonalCanvasHeight - p.size, p.y)); } }
function drawDandelion(p) { seasonalCtx.save(); seasonalCtx.globalAlpha = p.opacity; seasonalCtx.fillStyle = '#fff'; seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r * 0.5, 0, Math.PI * 2); seasonalCtx.fill(); for (let i = 0; i < 12; i++) { const angle = (Math.PI * 2 / 12) * i + p.angle; const rayLength = p.r * 2; seasonalCtx.beginPath(); seasonalCtx.moveTo(p.x, p.y); seasonalCtx.lineTo(p.x + Math.cos(angle) * rayLength, p.y + Math.sin(angle) * rayLength); seasonalCtx.strokeStyle = 'rgba(255,255,255,0.6)'; seasonalCtx.lineWidth = 0.5; seasonalCtx.stroke(); seasonalCtx.beginPath(); seasonalCtx.arc(p.x + Math.cos(angle) * rayLength, p.y + Math.sin(angle) * rayLength, p.r * 0.3, 0, Math.PI * 2); seasonalCtx.fill(); } seasonalCtx.restore(); p.y += p.speed; p.x += Math.sin(p.y * 0.05) * p.drift; p.angle += 0.01; if (p.y > seasonalCanvasHeight + p.r * 3) { p.y = -p.r * 3; p.x = Math.random() * seasonalCanvasWidth; } if (p.x > seasonalCanvasWidth + p.r * 3) p.x = -p.r * 3; if (p.x < -p.r * 3) p.x = seasonalCanvasWidth + p.r * 3; }
function drawTwinkle(p) { const twinkle = Math.sin(Date.now() * p.twinkleSpeed) * 0.5 + 0.5; seasonalCtx.save(); seasonalCtx.globalAlpha = p.opacity * twinkle; seasonalCtx.beginPath(); seasonalCtx.arc(p.x, p.y, p.r * (0.8 + twinkle * 0.4), 0, Math.PI * 2); seasonalCtx.fillStyle = p.color; seasonalCtx.shadowColor = p.color; seasonalCtx.shadowBlur = 5 + twinkle * 10; seasonalCtx.fill(); if (twinkle > 0.7) { const rayLength = p.r * 2 * twinkle; seasonalCtx.beginPath(); seasonalCtx.moveTo(p.x - rayLength, p.y); seasonalCtx.lineTo(p.x + rayLength, p.y); seasonalCtx.moveTo(p.x, p.y - rayLength); seasonalCtx.lineTo(p.x, p.y + rayLength); const diagLength = rayLength * 0.7; seasonalCtx.moveTo(p.x - diagLength, p.y - diagLength); seasonalCtx.lineTo(p.x + diagLength, p.y + diagLength); seasonalCtx.moveTo(p.x - diagLength, p.y + diagLength); seasonalCtx.lineTo(p.x + diagLength, p.y - diagLength); seasonalCtx.strokeStyle = p.color; seasonalCtx.lineWidth = 1; seasonalCtx.globalAlpha = p.opacity * twinkle * 0.5; seasonalCtx.stroke(); } seasonalCtx.restore(); p.y += Math.sin(Date.now() * 0.0005 + p.x) * p.speed * 50; p.x += Math.cos(Date.now() * 0.0005 + p.y) * p.speed * 50; if (p.y > seasonalCanvasHeight + p.r) p.y = -p.r; if (p.y < -p.r) p.y = seasonalCanvasHeight + p.r; if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; }
function drawConfetti(p) { seasonalCtx.save(); seasonalCtx.translate(p.x, p.y); seasonalCtx.rotate(p.rotation); seasonalCtx.fillStyle = p.color; switch (p.shape) { case 0: seasonalCtx.fillRect(-p.r / 2, -p.r / 2, p.r, p.r); break; case 1: seasonalCtx.beginPath(); seasonalCtx.arc(0, 0, p.r / 2, 0, Math.PI * 2); seasonalCtx.fill(); break; case 2: seasonalCtx.beginPath(); seasonalCtx.moveTo(0, -p.r / 2); seasonalCtx.lineTo(p.r / 2, p.r / 2); seasonalCtx.lineTo(-p.r / 2, p.r / 2); seasonalCtx.closePath(); seasonalCtx.fill(); break; } seasonalCtx.restore(); p.y += p.speed; p.x += Math.sin(p.rotation * 5 + p.y * 0.02) * p.drift; p.rotation += p.rotationSpeed; p.speed *= 0.99; if (p.y > seasonalCanvasHeight + p.r) { p.y = -p.r; p.x = Math.random() * seasonalCanvasWidth; p.speed = 1 + Math.random() * 3; } if (p.x > seasonalCanvasWidth + p.r) p.x = -p.r; if (p.x < -p.r) p.x = seasonalCanvasWidth + p.r; }
function drawRainbow(p) { if (p.fadeIn) { p.opacity += p.fadeSpeed; if (p.opacity >= p.maxOpacity) { p.opacity = p.maxOpacity; p.fadeIn = false; p.creationTime = Date.now(); } } seasonalCtx.save(); const gradient = seasonalCtx.createLinearGradient(0, 0, 0, seasonalCanvasHeight * 0.4); gradient.addColorStop(0, `rgba(255, 0, 0, ${p.opacity})`); gradient.addColorStop(0.17, `rgba(255, 165, 0, ${p.opacity})`); gradient.addColorStop(0.33, `rgba(255, 255, 0, ${p.opacity})`); gradient.addColorStop(0.5, `rgba(0, 255, 0, ${p.opacity})`); gradient.addColorStop(0.67, `rgba(0, 0, 255, ${p.opacity})`); gradient.addColorStop(0.83, `rgba(75, 0, 130, ${p.opacity})`); gradient.addColorStop(1, `rgba(148, 0, 211, ${p.opacity})`); seasonalCtx.globalCompositeOperation = 'lighter'; seasonalCtx.beginPath(); const centerX = seasonalCanvasWidth / 2; const centerY = seasonalCanvasHeight + seasonalCanvasHeight * 0.2; const radius = p.width * (p.opacity / p.maxOpacity); seasonalCtx.arc(centerX, centerY, radius, Math.PI, 0, true); seasonalCtx.lineWidth = seasonalCanvasHeight * 0.15 * (p.opacity / p.maxOpacity); seasonalCtx.strokeStyle = gradient; seasonalCtx.stroke(); seasonalCtx.restore(); }
function drawBud(p) { seasonalCtx.save(); seasonalCtx.globalAlpha = p.opacity; seasonalCtx.fillStyle = p.color; seasonalCtx.beginPath(); p.r += 0.01; if (p.r > 3) p.r = 3; seasonalCtx.arc(p.x, p.y, p.r, 0, Math.PI * 2); seasonalCtx.fill(); seasonalCtx.restore(); p.y += p.speed; p.x += Math.sin(p.y * 0.1) * p.drift; if (p.y > seasonalCanvasHeight + p.r) { p.y = -p.r; p.x = Math.random() * seasonalCanvasWidth; } }